// React/004-antd/src/components/Hello/index.tsx
/*
 * @Author       : heyongfeng
 * @Date         : 2021-09-17 10:52:13
 * @Description  :
 * @LastEditors  : heyongfeng
 * @LastEditTime : 2021-09-17 11:10:12
 */
import React, { Component } from 'react'
import { Button } from 'antd'

export default class Hello extends Component {
  render() {
    return (
      <>
        <h3>Hello React!</h3>
        <Button type="primary">我是一个antd按钮</Button>
      </>
    )
  }
}

// 05 Vue3/01_vue3/src/views/lesson6/Hello.vue
<!--
 * @Author       : heyongfeng
 * @Date         : 2021-04-25 20:31:51
 * @Description  :
 * @LastEditors  : heyongfeng
 * @LastEditTime : 2021-04-25 20:35:35
-->
<template>
  <div>
    <h3>{{ msg }}</h3>
    <button @click="msg='我是改变后的msg'">点击改变</button>
  </div>
</template>
<script>
export default {
  data() {
    return {
      msg: 'Hello'
    }
  },
  beforeCreate() {
    console.log('beforeCreate')
  },
  created() {
    console.log('created')
  },
  beforeMount() {
    console.log('beforeMount')
  },
  mounted() {
    console.log('mounted')
  },
  beforeUpdate() {
    console.log('beforeUpdate')
  },
  updated() {
    console.log('updated')
  },
  activated() {
    console.log('activated')
  },
  deactivated() {
    console.log('deactivated')
  },
  beforeUnmount() {
    console.log('beforeUnmount')
  },
  unmounted() {
    console.log('unmounted')
  }
}
</script>
